#!/usr/bin/env bash
set -Eeo pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

source ${dir}/nvm.sh

if [[ ! $(command -v pnpm) ]]; then
    npm install -g pnpm
fi

pnpm install
pnpm exec tsc --build --force
