#!/usr/bin/env bash
set -Eeo pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

source ${dir}/nvm.sh

if [[ ! $(command -v pnpm) ]]; then
    npm install -g pnpm
fi


function build() {
  pnpm install
  pnpm exec tsc --build --force
  pnpm test -r --filter=*test
}

function ci() {
  build
  pnpm publish -r --filter=!*test
}

command="${1-build}"
set +e; shift; set -Eeo pipefail;
$command "$@"