version: 2.1

commands:
  restore_nvm:
    description: "Restore NVM"
    steps:
      - restore:
          name: "Restore NVM"
          keys: nvm-{{ checksum ".nvmrc" }}
  save_nvm:
    description: "Save NVM"
    steps:
      - save:
          name: "Save NVM"
          key: nvm-{{ checksum ".nvmrc" }}
          paths:
            - ~/.nvm

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - restore_nvm
      - run:
          name: build
          command: ./run ci
      - store_artifacts:
          path: ./**/dist/
      - save_nvm


