version: 2.1

commands:
  restore_nvm_cache:
    description: "Restore NVM"
    steps:
      - restore_cache:
          name: Restore NVM
          keys:
            - nvm-{{ checksum ".nvmrc" }}
  save_nvm_cache:
    description: "Save NVM"
    steps:
      - save_cache:
          name: Save NVM
          key: nvm-{{ checksum ".nvmrc" }}
          paths:
            - ~/.nvm

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - restore_nvm_cache
      - run:
          name: build
          command: ./run ci
      - store_artifacts:
          path: ./**/dist/
      - save_nvm_cache


