version: 2.1

commands:
  restore_pnpm_cache:
    description: "Restore pnpm packages from CircleCI cache"
    steps:
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-v2-{{ checksum "pnpm.lock" }}
  save_pnpm_cache:
    description: "Save pnpm packages to CircleCI cache"
    steps:
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-v2-{{ checksum "pnpm.lock" }}
          paths:
            - ~/.cache/pnpm

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - restore_pnpm_cache
      - run:
          name: build
          command: ./run ci
      - store_artifacts:
          path: ./**/dist/
      - save_pnpm_cache


