version: 2.1

commands:
  restore_pnpm_cache:
    description: "Restore pnpm packages"
    steps:
      - restore_cache:
          name: restore
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
  save_pnpm_cache:
    description: "Save pnpm packages"
    steps:
      - save_cache:
          name: save
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.cache/pnpm

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - restore_pnpm_cache
      - run:
          name: build
          command: ./run ci
      - store_artifacts:
          path: ./**/dist/
      - save_pnpm_cache


